config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "welcome#index"

  get    "home",   to: "home#index"
  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get    "signup", to: "users#new"
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy] do
    member do
      get :following
      get :followers
    end
  end

  resources :tweets, only: [:index, :create, :destroy]
   
  resource  :relationship, only: [:create, :destroy]
  resolve("Relationship") { :relationship }

  get "help",  to: "static_pages#help"
  get "about", to: "static_pages#about"
end

app/views/shared/_error_messages.html.erb
<div class="alert alert-danger">
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_follow.html.erb
<%= form_with model: current_user.active_relationships.new(followed: user) do |form| %>
  <%= form.hidden_field :followed_id %>
  <%= form.submit "Follow", class: "btn btn-sm btn-primary" %>
<% end %>

app/views/shared/_profile.html.erb
<div class="d-flex justify-content-between mb-4">
  <div class="d-flex gap-3 align-items-center">
    <%= link_to gravatar_for(@user, size: 100), @user %>
    <div>
      <%= link_to @user.name, @user, class: "d-block fw-semibold fs-4 lh-sm text-dark" %>
      <div class="text-muted">@<%= @user.slug %></div>

      <small class="d-flex gap-3 mt-2">
        <div><%= link_to @user.following.count, following_user_path(@user), class: "text-dark fw-semibold" %> <span class="text-muted">Following</span></div>
        <div><%= link_to @user.followers.count, followers_user_path(@user), class: "text-dark fw-semibold" %> <span class="text-muted">Followers</span></div>
      </small>
    </div>
  </div>

  <% if logged_in? && current_user?(@user) %> 
    <div class="mt-3" id="follow_form">
      <% if current_user.following?(@user) %>
        <%= render 'shared/unfollow', user: @user %>
      <% else %>
        <%= render 'shared/follow', user: @user %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <table>
  <tr>
    <th>Tweets</th>
    <th>Following</th>
    <th>Followers</th>
  </tr>
  <tr>
    <td><%= link_to @user.tweets.count, user_path(@user) %></td>
    <td><%= link_to @user.following.count, following_user_path(@user) %></td>
    <td><%= link_to @user.followers.count, followers_user_path(@user) %></td>
  </tr>
  </table>
</div>

app/views/shared/_tweet_form.html.erb
<div>
  <%= form_with model: current_user.tweets.new do |form| %>
    <div class="field">
      <%= form.text_area :content, placeholder: "What is happening?", rows: 4, class: "rounded border border-secondary-subtle bg-light mb-2" %>
    </div>
    <div class="d-flex align-items-center justify-content-between">
      <label>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="text-muted" viewBox="0 0 16 16">
          <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
          <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54A.505.505 0 0 1 1 12.5v-9a.5.5 0 0 1 .5-.5h13z"/>
        </svg>
        <span class="d-none">
          <%= form.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
        </span>
      </label>

      <%= form.submit "Tweet", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/shared/_unfollow.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed: user), html: { method: :delete } do |form| %>
  <%= form.hidden_field :follower_id  %>
  <%= form.hidden_field :followed_id  %>
  <%= form.submit "Unfollow", class: "btn btn-large btn-secondary" %>
<% end %>

app/views/shared/_user_info.html.erb
<% @user ||= current_user  %>

<%= render 'shared/profile' %>
<%= render 'shared/tweet_form' if @user == current_user%>