config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "welcome#index"

  get    "home",   to: "home#index"
  get    "login",  to: "sessions#new"
  post   "login",  to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get    "signup", to: "users#new"
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy] do
    member do
      get :following
      get :followers
    end
  end

  resources :tweets, only: [:index, :create, :destroy]
   
  resource  :relationship, only: [:create, :destroy]
  resolve("Relationship") { :relationship }

  get "help",  to: "static_pages#help"
  get "about", to: "static_pages#about"
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <%= link_to "Help", help_path %>
  <%= link_to "About", about_path  %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top border-bottom">
  <div class="container d-flex gap-5 position-relative">
    <%= link_to "Tweeter", root_path, class: "text-dark fw-bold position-absolute", style: "right: 110%" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container collapse navbar-collapse px-0" id="navbarCollapse">
      <ul class="d-flex justify-content-between gap-3 navbar-nav mb-2 mb-md-0">
        <% if logged_in? %>
          <%# TODO: handle active class %>
          <li class="nav-item">
            <%= link_to users_path, class: 'nav-link d-flex gap-2 align-items-center', aria: { current: 'page' } do %>
              <%= inline_svg_tag("bootstrap-icons/people.svg") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to current_user, class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/person.svg") %>
              <span>Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path, class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/chat-left.svg") %>
              <span>Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_path(current_user), class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/gear.svg") %>
              <span>Settings</span>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete", class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/box-arrow-right.svg") %>
              <span>Sign out</span>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to users_path, class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/people.svg") %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to tweets_path, class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/chat-left.svg") %>
              <span>Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to login_path, class: 'nav-link d-flex gap-2 align-items-center' do %>
              <%= inline_svg_tag("bootstrap-icons/box-arrow-in-right.svg") %>
              <span>Sign in</span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main class="container mt-5">
      <%= yield %>
    </main>
  </body>
</html>